// lib/circuits/metadata.ts
// 2026 赛季赛道权威元数据字典 (主键: season + circuitId + layoutId)

import { CircuitMetadata } from './types';

export const CIRCUITS_METADATA: Record<string, CircuitMetadata> = {
  'albert_park': {
    circuitId: 'albert_park',
    layoutId: '2022-current',
    season: '2026',
    nameEn: 'Albert Park Circuit',
    nameZh: '阿尔伯特公园街区赛道',
    country: '澳大利亚',
    city: '墨尔本',
    lengthKm: 5.278,
    turns: 14,
    drsZones: 4,
    direction: 'clockwise',
    type: 'street',
    lapRecord: {"time":"1:19.813","driver":"Charles Leclerc","year":2024},
    svgFile: '/circuits/albert_park.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 580, y: 480 }
  },
  'shanghai': {
    circuitId: 'shanghai',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Shanghai International Circuit',
    nameZh: '上海国际赛车场',
    country: '中国',
    city: '上海',
    lengthKm: 5.451,
    turns: 16,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:32.238","driver":"Michael Schumacher","year":2004},
    svgFile: '/circuits/shanghai.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 380, y: 500 }
  },
  'suzuka': {
    circuitId: 'suzuka',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Suzuka International Racing Course',
    nameZh: '铃鹿国际赛车场',
    country: '日本',
    city: '铃鹿',
    lengthKm: 5.807,
    turns: 18,
    drsZones: 1,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:30.983","driver":"Lewis Hamilton","year":2019},
    svgFile: '/circuits/suzuka.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 500, y: 460 }
  },
  'miami': {
    circuitId: 'miami',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Miami International Autodrome',
    nameZh: '迈阿密国际赛道',
    country: '美国',
    city: '迈阿密',
    lengthKm: 5.412,
    turns: 19,
    drsZones: 3,
    direction: 'anti-clockwise',
    type: 'street',
    lapRecord: {"time":"1:29.708","driver":"Max Verstappen","year":2023},
    svgFile: '/circuits/miami.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 420, y: 520 }
  },
  'villeneuve': {
    circuitId: 'villeneuve',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Circuit Gilles Villeneuve',
    nameZh: '吉尔斯·维伦纽夫赛道',
    country: '加拿大',
    city: '蒙特利尔',
    lengthKm: 4.361,
    turns: 14,
    drsZones: 2,
    direction: 'clockwise',
    type: 'street',
    lapRecord: {"time":"1:13.078","driver":"Valtteri Bottas","year":2019},
    svgFile: '/circuits/villeneuve.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 260, y: 440 }
  },
  'monaco': {
    circuitId: 'monaco',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Circuit de Monaco',
    nameZh: '蒙特卡洛市街赛道',
    country: '摩纳哥',
    city: '蒙特卡洛',
    lengthKm: 3.337,
    turns: 19,
    drsZones: 1,
    direction: 'clockwise',
    type: 'street',
    lapRecord: {"time":"1:12.909","driver":"Lewis Hamilton","year":2021},
    svgFile: '/circuits/monaco.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 320, y: 480 }
  },
  'catalunya': {
    circuitId: 'catalunya',
    layoutId: 'grand-prix-no-chicane',
    season: '2026',
    nameEn: 'Circuit de Barcelona-Catalunya',
    nameZh: '加泰罗尼亚赛道',
    country: '西班牙',
    city: '巴塞罗那',
    lengthKm: 4.657,
    turns: 14,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:16.330","driver":"Max Verstappen","year":2023},
    svgFile: '/circuits/catalunya.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 420, y: 500 }
  },
  'red_bull_ring': {
    circuitId: 'red_bull_ring',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Red Bull Ring',
    nameZh: '红牛环赛道',
    country: '奥地利',
    city: '斯皮尔伯格',
    lengthKm: 4.318,
    turns: 10,
    drsZones: 3,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:05.619","driver":"Carlos Sainz","year":2020},
    svgFile: '/circuits/red_bull_ring.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 380, y: 460 }
  },
  'silverstone': {
    circuitId: 'silverstone',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Silverstone Circuit',
    nameZh: '银石赛道',
    country: '英国',
    city: '银石',
    lengthKm: 5.891,
    turns: 18,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:27.097","driver":"Max Verstappen","year":2020},
    svgFile: '/circuits/silverstone.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 420, y: 490 }
  },
  'spa': {
    circuitId: 'spa',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Circuit de Spa-Francorchamps',
    nameZh: '斯帕-弗朗科尔尚赛道',
    country: '比利时',
    city: '斯帕',
    lengthKm: 7.004,
    turns: 19,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:46.286","driver":"Valtteri Bottas","year":2018},
    svgFile: '/circuits/spa.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 360, y: 520 }
  },
  'hungaroring': {
    circuitId: 'hungaroring',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Hungaroring',
    nameZh: '亨格罗宁赛道',
    country: '匈牙利',
    city: '布达佩斯',
    lengthKm: 4.381,
    turns: 14,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:16.627","driver":"Lewis Hamilton","year":2020},
    svgFile: '/circuits/hungaroring.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 380, y: 480 }
  },
  'zandvoort': {
    circuitId: 'zandvoort',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Circuit Zandvoort',
    nameZh: '赞德福特赛道',
    country: '荷兰',
    city: '赞德福特',
    lengthKm: 4.259,
    turns: 14,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:11.097","driver":"Lewis Hamilton","year":2021},
    svgFile: '/circuits/zandvoort.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 440, y: 470 }
  },
  'monza': {
    circuitId: 'monza',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Autodromo Nazionale Monza',
    nameZh: '蒙扎国家赛车场',
    country: '意大利',
    city: '蒙扎',
    lengthKm: 5.793,
    turns: 11,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:21.046","driver":"Rubens Barrichello","year":2004},
    svgFile: '/circuits/monza.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 340, y: 500 }
  },
  'madring': {
    circuitId: 'madring',
    layoutId: '2026-debut',
    season: '2026',
    nameEn: 'Madring Circuit',
    nameZh: '马德里国际赛道',
    country: '西班牙',
    city: '马德里',
    lengthKm: 5.474,
    turns: 20,
    drsZones: 3,
    direction: 'clockwise',
    type: 'hybrid',
    lapRecord: {"time":"1:18.500","driver":"Simulation Baseline","year":2026},
    svgFile: '/circuits/madring.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 380, y: 510 }
  },
  'baku': {
    circuitId: 'baku',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Baku City Circuit',
    nameZh: '巴库市街赛道',
    country: '阿塞拜疆',
    city: '巴库',
    lengthKm: 6.003,
    turns: 20,
    drsZones: 2,
    direction: 'anti-clockwise',
    type: 'street',
    lapRecord: {"time":"1:43.009","driver":"Charles Leclerc","year":2019},
    svgFile: '/circuits/baku.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 480, y: 520 }
  },
  'sepang': {
    circuitId: 'sepang',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Sepang International Circuit',
    nameZh: '雪邦国际赛车场',
    country: '马来西亚',
    city: '吉隆坡',
    lengthKm: 5.543,
    turns: 15,
    drsZones: 2,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:34.080","driver":"Sebastian Vettel","year":2017},
    svgFile: '/circuits/sepang.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 420, y: 480 }
  },
  'marina_bay': {
    circuitId: 'marina_bay',
    layoutId: '2023-current',
    season: '2026',
    nameEn: 'Marina Bay Street Circuit',
    nameZh: '滨海湾市街赛道',
    country: '新加坡',
    city: '新加坡',
    lengthKm: 4.94,
    turns: 19,
    drsZones: 4,
    direction: 'anti-clockwise',
    type: 'street',
    lapRecord: {"time":"1:34.486","driver":"Daniel Ricciardo","year":2024},
    svgFile: '/circuits/marina_bay.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 480, y: 500 }
  },
  'americas': {
    circuitId: 'americas',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Circuit of the Americas',
    nameZh: '美洲赛道 (COTA)',
    country: '美国',
    city: '奥斯汀',
    lengthKm: 5.513,
    turns: 20,
    drsZones: 2,
    direction: 'anti-clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:36.169","driver":"Charles Leclerc","year":2019},
    svgFile: '/circuits/americas.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 360, y: 520 }
  },
  'rodriguez': {
    circuitId: 'rodriguez',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Autódromo Hermanos Rodríguez',
    nameZh: '罗德里格斯兄弟赛车场',
    country: '墨西哥',
    city: '墨西哥城',
    lengthKm: 4.304,
    turns: 17,
    drsZones: 3,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:17.774","driver":"Valtteri Bottas","year":2021},
    svgFile: '/circuits/rodriguez.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 380, y: 480 }
  },
  'interlagos': {
    circuitId: 'interlagos',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Autódromo José Carlos Pace (Interlagos)',
    nameZh: '英特拉格斯赛道',
    country: '巴西',
    city: '圣保罗',
    lengthKm: 4.309,
    turns: 15,
    drsZones: 2,
    direction: 'anti-clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:10.540","driver":"Valtteri Bottas","year":2018},
    svgFile: '/circuits/interlagos.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 420, y: 500 }
  },
  'vegas': {
    circuitId: 'vegas',
    layoutId: 'strip-circuit',
    season: '2026',
    nameEn: 'Las Vegas Strip Circuit',
    nameZh: '拉斯维加斯街道赛道',
    country: '美国',
    city: '拉斯维加斯',
    lengthKm: 6.201,
    turns: 17,
    drsZones: 2,
    direction: 'anti-clockwise',
    type: 'street',
    lapRecord: {"time":"1:35.490","driver":"Oscar Piastri","year":2023},
    svgFile: '/circuits/vegas.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 380, y: 520 }
  },
  'losail': {
    circuitId: 'losail',
    layoutId: 'grand-prix',
    season: '2026',
    nameEn: 'Lusail International Circuit',
    nameZh: '卢赛尔国际赛车场',
    country: '卡塔尔',
    city: '卢赛尔',
    lengthKm: 5.419,
    turns: 16,
    drsZones: 1,
    direction: 'clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:24.319","driver":"Max Verstappen","year":2023},
    svgFile: '/circuits/losail.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 420, y: 500 }
  },
  'yas_marina': {
    circuitId: 'yas_marina',
    layoutId: '2021-current',
    season: '2026',
    nameEn: 'Yas Marina Circuit',
    nameZh: '亚斯码头赛道',
    country: '阿联酋',
    city: '阿布扎比',
    lengthKm: 5.281,
    turns: 16,
    drsZones: 2,
    direction: 'anti-clockwise',
    type: 'permanent',
    lapRecord: {"time":"1:26.103","driver":"Max Verstappen","year":2021},
    svgFile: '/circuits/yas_marina.svg',
    viewBox: '0 0 800 600',
    startFinish: { x: 400, y: 520 }
  }
};
